export const GET_ALL_DOC_REQUEST = "GET_ALL_DOC_REQUEST";
export const GET_ALL_DOC_SUCCESS = "GET_ALL_DOC_SUCCESS";
export const GET_ALL_DOC_FAILURE = "GET_ALL_DOC_FAILURE";

export const DELETE_DOC_REQUEST = "DELETE_DOC_REQUEST";
export const DELETE_DOC_SUCCESS = "DELETE_DOC_SUCCESS";
export const DELETE_DOC_FAILURE = "DELETE_DOC_FAILURE";

export const UPDATE_TITLE_REQUEST = "UPDATE_TITLE_REQUEST";
export const UPDATE_TITLE_SUCCESS = "UPDATE_TITLE_SUCCESS";
export const UPDATE_TITLE_FAILURE = "UPDATE_TITLE_FAILURE";

export const ADD_USER_REQUEST = "ADD_USER_REQUEST";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const ADD_USER_FAILURE = "ADD_USER_FAILURE";
export const NO_USER = "NO_USER";

export const CREATE_NEW_DOC_REQUEST = "CREATE_NEW_DOC_REQUEST";
export const CREATE_NEW_DOC_SUCCESS = "CREATE_NEW_DOC_SUCCESS";
export const CREATE_NEW_DOC_FAILURE = "CREATE_NEW_DOC_FAILURE";
